# Generated by Django 5.1.1 on 2024-11-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_pontuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('custo', models.PositiveIntegerField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
