# Generated by Django 5.1.1 on 2024-10-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_agendamento_empresa_delete_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='endereco',
            field=models.CharField(default='Não disponível', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipos_residuos',
            field=models.TextField(max_length=150),
        ),
    ]
