# Generated by Django 5.1.1 on 2024-11-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='etapa_atual',
            field=models.CharField(choices=[('solicitacao', 'Solicitação de Agendamento'), ('coleta', 'Coleta'), ('triagem', 'Triagem'), ('transformacao', 'Transformação'), ('realocacao', 'Realocação')], default='solicitacao', max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('solicitacao', 'Solicitação'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='solicitacao', max_length=20),
        ),
    ]
