# Generated by Django 5.1.1 on 2024-11-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0007_centrocoleta_latitude_centrocoleta_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocoleta',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='centrocoleta',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
